on:
  workflow_dispatch:

name: template

jobs:
  test-latex-template:
    runs-on: ubuntu-latest
    name: Test LaTeX Template 
    steps: 
      - uses: actions/checkout@v2
      - name: Build
        run: |
          docker pull mbredel/thesis-template:latest
          docker run --volume $(pwd):/thesis-template/ mbredel/thesis-template:latest
